version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_reservas_vuelos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  flask:
    build: .
    container_name: flask_reservas
    restart: always
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql+pymysql://reservas_user:reservas_pass@mysql:3306/sistema_reservas_vuelos
      FLASK_ENV: development
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
